server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${ip}:3306/ssm?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
        username: root
        password: zeng.040122
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB

ip: localhost

